calcroyalties/src/app/views/wellevent.py
from flask import Blueprint, request, config, redirect, url_for, abort, render_template, flash, Response
import json, io, csv

import config
from .permission_handler import PermissionHandler
from src.util.apperror import AppError
from .main import get_proddate

wellevent = Blueprint('wellevent', __name__)

@wellevent.route('/wellevent/search', methods=['GET'])
def search():
    if not request.args: return render_template('wellevent/search.html')
    statement = """SELECT WellEventInfo.WellEvent, RTAHeader.RTPOperator, WellEventStatus.Status, WellLicence.Licensee, BAInfo.CorpShortName, WellFacilitylink.Facility, FacilityInfo.Name, WellEventLoc.Lat, WellEventLoc.Long
    FROM WellEventInfo
    LEFT OUTER JOIN RTAHeader ON WellEventInfo.WellEvent = RTAHeader.WellEvent
    AND (DATE('{proddate}') BETWEEN RTAHeader.StartDate AND RTAHeader.EndDate OR RTAHeader.StartDate IS NULL OR RTAHeader.StartDate = '')
    LEFT OUTER JOIN WellEventStatus ON WellEventInfo.WellEvent = WellEventStatus.WellEvent
    AND (DATE('{proddate}') BETWEEN WellEventStatus.StartDate AND WellEventStatus.EndDate OR WellEventStatus.StartDate IS NULL OR WellEventStatus.StartDate = '')
    LEFT OUTER JOIN BAInfo ON RTAHeader.RTPOperator = BAInfo.BAid
    AND (DATE('{proddate}') BETWEEN BAInfo.StartDate AND BAInfo.EndDate OR BAInfo.StartDate IS NULL OR BAInfo.StartDate = '')
    LEFT OUTER JOIN WellFacilityLink ON WellEventInfo.WellEvent = WellFacilityLink.WellEvent
    AND (DATE('{proddate}') BETWEEN WellFacilityLink.StartDate AND WellFacilityLink.EndDate OR WellFacilityLink.StartDate IS NULL OR WellFacilityLink.StartDate = '')
    LEFT OUTER JOIN FacilityInfo ON FacilityInfo.Facility = WellFacilityLink.Facility
    AND (DATE('{proddate}') BETWEEN FacilityInfo.StartDate AND FacilityInfo.EndDate OR FacilityInfo.StartDate IS NULL OR FacilityInfo.StartDate = '')
    LEFT OUTER JOIN WellEventLoc ON WellEventInfo.WellEvent = WellEventLoc.WellEvent
    LEFT OUTER JOIN WellInfo ON WellEventInfo.Well = WellInfo.Well
    AND (DATE('{proddate}') BETWEEN WellInfo.StartDate AND WellInfo.EndDate OR WellInfo.StartDate IS NULL OR WellInfo.StartDate = '')
    LEFT OUTER JOIN WellLicence ON WellLicence.WellLicence = WellInfo.WellLicence
    AND (DATE('{proddate}') BETWEEN WellLicence.StartDate AND WellLicence.EndDate OR WellLicence.StartDate IS NULL OR WellLicence.StartDate = '')
    WHERE (DATE('{proddate}') BETWEEN WellEventInfo.StartDate AND WellEventInfo.EndDate OR WellEventInfo.StartDate IS NULL OR WellEventInfo.StartDate = '')""".format(proddate=get_proddate())

    db = config.get_database()
    # the following allows us to check incoming arguments against a dictionary of allowed ones and match them with a relevant table name:
    argument_tables = {'WellEvent': 'WellEventInfo', 'Licensee': 'WellLicence', 'RTPOperator': 'RTAHeader', 'LSD': 'WellEventInfo', 'Section': 'WellEventInfo', 'Township': 'WellEventInfo', 'Range': 'WellEventInfo', 'Meridian': 'WellEventInfo'}
    kwargs = dict((k, v) for k, v in request.args.items() if v)  # this is to get rid of empty values coming from forms
    search_arguments = ""
    for arg in kwargs:
        if arg in argument_tables:
            compound = argument_tables[arg] + '.' + arg + '=' + '"' + kwargs[arg] + '"'
            search_arguments += " AND " + compound

    results = db.select_sql(statement + search_arguments)
    d = request.args.to_dict()
    output = 'browse'
    print('The Request is:',request.args.to_dict())
    if 'Output' in d:
        if d['Output'] == 'map':
            output = "map"
        elif d['Output'] == 'excel':
            output = "excel"
    print('The output is:',output)
    if results:
        if output == 'map':
            points = []
            for result in results:
                if result.Long:
                    json_obj = {}
                    json_obj['type'] = 'Feature'
                    json_obj['properties'] = {}
                    json_obj['properties']['name'] = result.WellEvent
                    json_obj['properties']['popupContent'] = '<b>%s</b> <br> Pool Name: %s<br><a href="/wellevent/%s">Details</a>' % (
                        result.WellEvent, result.RTPOperator, result.WellEvent)
                    json_obj['geometry'] = {}
                    json_obj['geometry']['type'] = 'Point'
                    json_obj['geometry']['coordinates'] = [round(result.Long * -1, 5), round(result.Lat, 5)]
                    points.append(json_obj)
            print('***** points: ', json.dumps(points))
            print('Center is...:',center_point(points))
            return render_template('map.html', results=json.dumps(points), center=center_point(points))

        elif output == 'excel':
            """ Export relies on python's csv module to generate csv, StringIO writer to simulate a file for csv,
                as we don't need to save it on hard drive, and dbi.execute and cursor to get raw results of a query
                as that's what we need for csv to work properly"""
            db.dbi.execute(statement + search_arguments)
            output = io.StringIO()
            writer = csv.writer(output, quoting=csv.QUOTE_NONNUMERIC)
            writer.writerow([i[0] for i in db.dbi.cursor.description])
            writer.writerows(db.dbi.cursor)
            return Response(output.getvalue(), mimetype="text/csv", headers={"Content-disposition": "attachment; filename=WellEvent_export.csv"})

        else:
            return render_template('wellevent/search.html', results=results, search_terms=request.args.to_dict())
    else:
        flash('No results found.')
        return render_template('wellevent/search.html', search_terms=request.args.to_dict())

@wellevent.route('/wellevent/')
def handle_redirect():
    return redirect(url_for('wellevent.search'))

@wellevent.route('/wellevent/<wellevent_num>')
def details(wellevent_num):
    if not wellevent_num: redirect(url_for('wellevent.search'))
    try:
        db = config.get_database()
        statement="""SELECT WellEventInfo.*, RTAMineralOwnership.Product
        FROM WellEventInfo
        LEFT OUTER JOIN RTAMineralOwnership ON WellEventInfo.WellEvent = RTAMineralOwnership.WellEvent
        AND (DATE('{proddate}') BETWEEN RTAMineralOwnership.StartDate AND RTAMineralOwnership.EndDate)
        WHERE (DATE('{proddate}') BETWEEN WellEventInfo.StartDate AND WellEventInfo.EndDate)
        AND WellEventInfo.WellEvent = '{wellevent}'""".format(proddate=get_proddate(), wellevent=wellevent_num)
        wellevent = db.select_sql(statement)[0]
    except Exception as e:
        print(e)
        abort(404)

    statement_volumetric = """SELECT * From VolumetricInfo WHERE FromTo = '{wellevent}' AND DATE(ProdMonth) = DATE('{proddate}')""".format(wellevent=wellevent_num, proddate=get_proddate())
    volumetric = db.select_sql(statement_volumetric)

    well = db.select1('WellRoyaltyMaster', WellEvent=wellevent_num)

    statement_leases = """SELECT Lease.*, WellLeaseLink.PEFNInterest FROM Lease, WellLeaseLink WHERE WellLeaseLink.WellEvent="%s" AND Lease.ID=WellLeaseLink.LeaseID"""
    leases = db.select_sql(statement_leases % wellevent_num)

    statement_facilities = """SELECT FacilityInfo.* FROM FacilityInfo, WellFacilitylink WHERE FacilityInfo.Facility=WellFacilitylink.Facility AND WellFacilitylink.WellEvent="%s" """
    facilities = db.select_sql(statement_facilities % wellevent_num)
    return render_template('wellevent/details.html', wellevent=wellevent, leases=leases, facilities=facilities, volumetric=volumetric, well=well)

def center_point(points):
    x,y  = points[0]['geometry']['coordinates']
    ux = x
    lx = x
    uy = y
    ly = y
    # print('---start',x,y)
    for point in points:
        x,y = point['geometry']['coordinates']
        if x > ux : ux = x
        if x < lx : lx = x
        if y > uy : uy = y
        if y < ly : ly = y
        # print('---',point['geometry']['coordinates'])

    # print('+++', ux, lx)
    # print('+++', uy, ly)
    return (lx + ((ux - lx) / 2)), (ly + ((uy - ly) / 2))

calcroyalties/src/app/views/worksheet.py
import sys
import traceback
from flask import Blueprint, request, config, render_template

import config
from src.util.apperror import AppError
from src.util.appdate import prod_month_to_date
from src.util.app_formatter import format_gorr
from src.database.data_structure import DataStructure
import pdfkit

worksheet = Blueprint('worksheet', __name__)


@worksheet.route('/worksheet')
def calc_worksheet():
    args = request.args.to_dict()
    db = config.get_database()
    calcs = db.select('Calc', **args)
    result = ""
    for calc in calcs:
        result += generate_worksheet_from_calc(calc)
        # result += "<hr>"

    return result


@worksheet.route('/worksheettopdf')
def calc_worksheettopdf():
    try:
        args = request.args.to_dict()
        print(args)
        db = config.get_database()
        calcs = db.select('Calc', **args)
        result = ""
        for calc in calcs:
            result += generate_worksheet_from_calc(calc, 'n')
            result += "<hr>"

        # text_file = open("out.html", "w", encoding="utf-8")
        # text_file.write(result)
        # text_file.write(result. .encode("UTF-8"))
        # text_file.close()

        print("about to set path")
        path_wkthmltopdf = r'C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe'
        print("about to set config")
        configpdf = pdfkit.configuration(wkhtmltopdf=path_wkthmltopdf)
        print("about to pdfkit")
        pdfkit.from_string(result, 'out.pdf', configuration=configpdf)

        return "pdf should have been created"

    except Exception as e:
        print('PDF worksheet: ***Error:', e)
        traceback.print_exc(file=sys.stdout)
        tb = traceback.format_exc()
        return "<h2>Error generating pdf" + \
               '<plaintext>' + tb + '</plaintext>'


def generate_worksheet_from_calc(calc, with_js='y'):
    """
    Generate html for the calc row that is passed
    :param calc: a full calc record
    :param with_js: default is 'y' only other option is 'n' and should only be used to work around a
                    pdf generation issue
    :return: html of the worksheet for the calc record
    """
    try:
        db = config.get_database()
        if calc.Entity == 'Well':
            well = db.select1('WellRoyaltyMaster', ID=calc.EntityID)
        else:
            well = None
        entity_lease_link_array = db.select('EntityLeaseLink', Entity=calc.Entity, EntityID=calc.EntityID)
        if len(entity_lease_link_array) == 0:
            raise AppError("There were no well_lease_link records for " + str(calc.WellID) + str(calc.ProdMonth))
        entity_lease_link = entity_lease_link_array[0]
        royalty = db.select1('LeaseRoyaltyMaster', ID=calc.LeaseID)
        lease = db.select1('Lease', ID=calc.LeaseID)

        history = db.select_sql("""SELECT *
                   from Calc
                   WHERE ProdMonth = "{}" and LeaseID = "{}" and Entity = "{}" and EntityID = "{}"
                   and Product = "{}" and RPBA = "{}"
                   order by ExtractDate""".format(calc.ProdMonth, calc.LeaseID, calc.Entity, calc.EntityID,
                                                  calc.Product, calc.RPBA))
        # history = db.select_sql("""SELECT ID, ExtractDate, BaseNetRoyaltyValue, GorrNetRoyaltyValue
        #            from Calc
        #            WHERE ProdMonth = "{}" and LeaseID = "{}" and Entity = "{}" and EntityID = "{}"
        #            and Product = "{}" and RPBA = "{}"
        #            order by ExtractDate""".format(calc.ProdMonth, calc.LeaseID, calc.Entity, calc.EntityID,
        #                                           calc.Product, calc.RPBA))

        prev_BaseNetRoyaltyValue = 0.0
        prev_GorrNetRoyaltyValue = 0.0
        i = 0
        for h in history:
            h.BookedBaseNetRoyaltyValue = h.BaseNetRoyaltyValue - prev_BaseNetRoyaltyValue
            h.BookedGorrNetRoyaltyValue = h.GorrNetRoyaltyValue - prev_GorrNetRoyaltyValue
            h.Booked = h.BookedBaseNetRoyaltyValue + h.BookedGorrNetRoyaltyValue
            prev_BaseNetRoyaltyValue = h.BaseNetRoyaltyValue
            prev_GorrNetRoyaltyValue = h.GorrNetRoyaltyValue
            # Set the original calc record to the history record the one before this one
            if h.ExtractDate == calc.ExtractDate and i > 0:
                calc.original(history[i-1])

            i += 1

        monthly_array = db.select('Monthly', ExtractDate=calc.ExtractDate, Entity=calc.Entity, EntityID=calc.EntityID,
                                  prodMonth=calc.ProdMonth, product=calc.Product, RPBA=calc.RPBA)
        if len(monthly_array) == 0:
            raise AppError("There were no monthly records for well: " + str(calc.WellID) + " ProdDate: " +
                           str(calc.ProdMonth) + " Product: " + calc.Product)
        monthly = monthly_array[0]  # if there are multiple pick the first one

        ba = db.select1('BAInfo', BAid=monthly.RPBA, BAType='RTP')

        calc_specific = DataStructure(calc.RoyaltySpecific)
        rtp_info = db.select1('RTPInfo', WellEvent=well.WellEvent, Product=calc.Product, Payer=monthly.RPBA,
                              Date=prod_month_to_date(calc.ProdMonth))

        royalty.format_gorr = format_gorr(calc.Gorr)

        return render_template('worksheet/calc_worksheet.html',
                               with_js=with_js,
                               well=well, rm=royalty, m=monthly, lease=lease,
                               calc=calc, calc_sp=calc_specific, entity_lease_link=entity_lease_link,
                               ba=ba, rtp_info=rtp_info, history=history)
    except Exception as e:
        print('views.worksheet: ***Error:', e)
        traceback.print_exc(file=sys.stdout)
        tb = traceback.format_exc()
        return "<h2>Error displaying worksheet for " + calc.Entity + " %s</h2><br>" % calc.EntityID + str(e) + \
               '<plaintext>' + tb + '</plaintext>'


def generate_pdfworksheet_from_calc(calc):
    try:
        db = config.get_database()
        if calc.Entity == 'Well':
            well = db.select1('WellRoyaltyMaster', ID=calc.EntityID)
        else:
            well = None
        entity_lease_link_array = db.select('EntityLeaseLink', Entity=calc.Entity, EntityID=calc.EntityID)
        if len(entity_lease_link_array) == 0:
            raise AppError("There were no well_lease_link records for " + str(calc.WellID) + str(calc.ProdMonth))
        entity_lease_link = entity_lease_link_array[0]
        royalty = db.select1('LeaseRoyaltyMaster', ID=calc.LeaseID)
        lease = db.select1('Lease', ID=calc.LeaseID)

        history = db.select_sql("""SELECT ID, ExtractDate, BaseNetRoyaltyValue, GorrNetRoyaltyValue
                   from Calc
                   WHERE ProdMonth = "{}" and LeaseID = "{}" and Entity = "{}" and EntityID = "{}"
                   and Product = "{}" and RPBA = "{}"
                   order by ExtractDate""".format(calc.ProdMonth, calc.LeaseID, calc.Entity, calc.EntityID,
                                                  calc.Product, calc.RPBA))

        prev_BaseNetRoyaltyValue = 0.0
        prev_GorrNetRoyaltyValue = 0.0
        for h in history:
            h.BookedBaseNetRoyaltyValue = h.BaseNetRoyaltyValue - prev_BaseNetRoyaltyValue
            h.BookedGorrNetRoyaltyValue = h.GorrNetRoyaltyValue - prev_GorrNetRoyaltyValue
            h.Booked = h.BookedBaseNetRoyaltyValue + h.BookedGorrNetRoyaltyValue
            prev_BaseNetRoyaltyValue = h.BaseNetRoyaltyValue
            prev_GorrNetRoyaltyValue = h.GorrNetRoyaltyValue

        monthly_array = db.select('Monthly', ExtractDate=calc.ExtractDate, Entity=calc.Entity, EntityID=calc.EntityID,
                                  prodMonth=calc.ProdMonth, product=calc.Product, RPBA=calc.RPBA)
        if len(monthly_array) == 0:
            raise AppError("There were no monthly records for well: " + str(calc.WellID) + " ProdDate: " +
                           str(calc.ProdMonth) + " Product: " + calc.Product)
        monthly = monthly_array[0]  # if there are multiple pick the first one

        ba = db.select1('BAInfo', BAid=monthly.RPBA, BAType='RTP')

        calc_specific = DataStructure(calc.RoyaltySpecific)
        rtp_info = db.select1('RTPInfo', WellEvent=well.WellEvent, Product=calc.Product, Payer=monthly.RPBA,
                              Date=prod_month_to_date(calc.ProdMonth))

        royalty.format_gorr = format_gorr(calc.Gorr)

        return render_template('worksheet/pdfcalc_worksheet.html',
                               well=well, rm=royalty, m=monthly, lease=lease,
                               calc=calc, calc_sp=calc_specific, entity_lease_link=entity_lease_link,
                               ba=ba, rtp_info=rtp_info, history=history)
    except Exception as e:
        print('views.worksheet: ***Error:', e)
        traceback.print_exc(file=sys.stdout)
        tb = traceback.format_exc()
        return "<h2>Error displaying worksheet for " + calc.Entity + " %s</h2><br>" % calc.EntityID + str(e) + \
               '<plaintext>' + tb + '</plaintext>'

calcroyalties/src/app/templates/facility_search.html
{% extends "layout.html" %}
{% block body %}
<script>
  $(function() {
  	$('#tabs').tabs();
    $('#accordion').accordion({
      collapsible:true,
      heightStyle:'content',
    });
    $('#search-basic, #search-advanced').button({
      icons: {primary: 'ui-icon-search'}
    });
  });
</script>

<h2>Facility Search</h2>

<div id="accordion">
  <h3>Search Criteria</h3>
  <div>
  	<div id="tabs">
  	  <ul>
  	    <li><a href="#tabs-basic">Basic search</a></li>
  	    <li><a href="#tabs-advanced">Advanced search</a></li>
  	  </ul>

  	  <div id="tabs-basic">
  	    Facility ID
        <br>
        <input id='facility-search-id'></input>
        <br>
        <br>
        Sub Type
        <br>
        <input id='facility-search-subtype'></input>
        <br>
        <br>
        <button id='search-basic'>Search</button>
  	  </div>

  	  <div id="tabs-advanced">
  	    Meridian
        <br>
        <input id='facility-search-prov'></input>
        <br>
        <br>
        Township
        <br>
        <input id='facility-search-township'></input>
        <br>
        <br>
        <button id='search-advanced'>Search</button>
  	  </div>

  	</div>
  </div>
</div>

<div id='results-table'>
</div>

<script>
  $('#search-basic, #search-advanced').click(function() {
    // console.log('hello');
    $.ajax({
      url: "/api/facility_results",
      dataType: "html"
    })
      .done(function (msg){
        $('#results-table').html(msg);
        $("tr:even").css("background-color", "lightgray");
        $("#accordion").accordion("option", "active", false)
    });
  });
</script>
</html>

{% endblock %}
<!--
When searching, send the search parameters from this form as a post request to the server.
When displaying results, display the same template (this page) but also pass on the search results. Then, if search results are passed:
- collapse the search parameters accordion;
- unhide results table
- prepopulate results table with results
-->

calcroyalties/src/app/templates/index.html
{% extends "layout.html" %}
{% block body %}
<div align="center">
<p style="width:400px">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

calcroyalties/src/app/templates/lease_details.html
{% extends 'layout.html' %}
{% block body %}

<h3>Lease {{ lease.ID }}</h3>

<table class="wellmodal table-striped">
    <tr>
        <th>ID</th>
        <th>Lease Type</th>
        <th>Rights Granted</th>
        <th>Royalty Scheme</th>
        <th>Crown Multiplier</th>
        <th>Province</th>
        <th>Lessor</th>
    </tr>
    <tr>
        <td>{{ lease.ID }} </td>
        <td>{{ lease.LeaseType }} </td>
        <td>{{ royaltymaster.RightsGranted }} </td>
        <td>{{ royaltymaster.RoyaltyScheme }} </td>
        <td>{{ royaltymaster.CrownMultiplier }} </td>
        <td>{{ lease.Province }} </td>
        <td>{{ lease.Lessor }} </td>
    </tr>
</table>

{% endblock %}

calcroyalties/src/app/templates/lease_info.html
{% extends 'layout.html' %}
{% block body %}

<h3>Lease {{ lease.ID }}</h3>

<table class="wellmodal table-striped">
    <tr>
        <th>ID</th>
        <th>Lease Type</th>
        <th>Rights Granted</th>
        <th>Royalty Scheme</th>
        <th>Crown Multiplier</th>
        <th>Province</th>
        <th>Lessor</th>
    </tr>
    <tr>
        <td>{{ lease.ID }} </td>
        <td>{{ lease.LeaseType }} </td>
        <td>{{ royaltymaster.RightsGranted }} </td>
        <td>{{ royaltymaster.RoyaltyScheme }} </td>
        <td>{{ royaltymaster.CrownMultiplier }} </td>
        <td>{{ lease.Province }} </td>
        <td>{{ lease.Lessor }} </td>
    </tr>
</table>

{% endblock %}

calcroyalties/src/app/templates/lease_search.html
{% extends "layout.html" %}
{% block body %}
<script>
  $(function() {
  	$('#tabs').tabs();
    $('#accordion').accordion({
      collapsible:true,
      heightStyle:'content',
    });
    $('#search-basic, #search-advanced').button({
      icons: {primary: 'ui-icon-search'}
    });
  });
</script>

<h2>Lease Search</h2>

<div id="accordion">
  <h3>Search Criteria</h3>
  <div>
  	<div id="tabs">
  	  <ul>
  	    <li><a href="#tabs-basic">Basic search</a></li>
  	    <li><a href="#tabs-advanced">Advanced search</a></li>
  	  </ul>

  	  <div id="tabs-basic">
      <form name="search-basic">
  	    Lease ID
        <br>
        <input id='ID' name="ID"></input>
        <br>
        <br>
        Province
        <br>
        <input id='Prov' name="Prov"></input>
        <br>
        <br>
        <button type="submit" id='search-basic'>Search</button>
       </form>
  	  </div>

  	  <div id="tabs-advanced">
      <form name="search-advanced">
  	    Province
        <br>
        <input id='well-search-prov' name="Province"></input>
        <br>
        <br>
        Well Type
        <br>
        <input id='well-search-type' name="WellType"></input>
        <br>
        <br>
        <button type="submit" id='search-advanced'>Search</button>
      </form>
  	  </div>

  	</div>
  </div>
</div>

<div id='results-table'>
</div>

<script>
$('form[name="search-basic"]').submit(function() {
  event.preventDefault();
  $.ajax({
    url: "/api/leaseresults",
    dataType: "html",
    method: "POST",
    contentType: "application/json",
    data: JSON.stringify(formToDict(document.forms["search-basic"])),
  })
  .done(function(msg) {
    $('#results-table').html(msg);
    $("#accordion").accordion("option", "active", false)
  })
  .fail(function() {
    $('#results-table').html('No results were found');
  })
  });

  function formToDict(oForm) {
    var dict = {};
    for (i = 0; i < oForm.length; i++) {
      if (oForm.elements[i].name != '') {
        if (oForm.elements[i].type == 'text' || oForm.elements[i].type == 'hidden') {
          dict[oForm.elements[i].name] = oForm.elements[i].value;
        } else if (oForm.elements[i].type == 'checkbox') {
          dict[oForm.elements[i].name] = oForm.elements[i].checked;
        } else {
          console.log('*** did not handle: ' + oForm.elements[i].name + "," + oForm.elements[i].value + "," + oForm.elements[i].type)
        };
      }
    }
    return dict
  }

</script>

</html>

{% endblock %}

calcroyalties/src/app/templates/login.html
{% extends "layout.html" %}
{% block body %}
<h3>Please login to continue:</h3>
<div id="login_form">
    <form action="/login" method="POST"">
        <label>Username:</label>
        &nbsp;
        <input name="login" id="login" type="text">
        <br><br>
        <button type="submit">Login</button>
    </form>
</div>
{% endblock %}

calcroyalties/src/app/templates/wellevent_search.html
{% extends "layout.html" %}
{% block body %}
<script>
  $(function() {
  	$('#tabs').tabs();
    $('#accordion').accordion({
      collapsible:true,
      heightStyle:'content',
    });
    $('#search-basic, #search-advanced').button({
      icons: {primary: 'ui-icon-search'}
    });
  });
</script>

<h2>Well Event Search</h2>

<div id="accordion">
  <h3>Search Criteria</h3>
  <div>
  	<div id="tabs">
  	  <ul>
  	    <li><a href="#tabs-basic">Basic search</a></li>
  	    <li><a href="#tabs-advanced">Advanced search</a></li>
  	  </ul>

  	  <div id="tabs-basic">
      <form name="search-basic" action="/wellevent/search" method="get">
  	    Well Event
        <br>
        <input id='ID' name="WellEvent" value="{% if search_terms %}{{ search_terms['WellEvent'] }}{% endif%}" />
        <br>
        <br>
        Meridian
        <br>
        <input id='Prov' name="Meridian" value="{% if search_terms %}{{ search_terms['Meridian'] }}{% endif%}" />
        <br>
        <br>
        <button type="submit" id='search-basic'>Search</button>
       </form>
  	  </div>

  	  <div id="tabs-advanced">
      <form name="search-advanced">
  	    Province
        <br>
        <input id='well-search-prov' name="Province" />
        <br>
        <br>
        Well Type
        <br>
        <input id='well-search-type' name="WellType" />
        <br>
        <br>
        <button type="submit" id='search-advanced'>Search</button>
      </form>
  	  </div>

  	</div>
  </div>
</div>

{% if results %}
<div id='results-table'>
<table style="width:100%" class="results_table table-striped">
  <tr>
    <td colspan=13><b>{{results|length}}</b> results found</td>
  </tr>
  <tr>
    <th>Well Event</th>
    <th>RTPOperator</th>
    <th>Status</th>
    <th>Operator Short Name</th>
    <th>Meridian</th>
    <th>Actions</th>
  </tr>
  {% for row in results %}
  <tr>
    <td>{{ row.WellEvent or "" }}</td>
    <td>{{ row.RTPOperator or "" }}</td>
    <td>{{ row.Status or "" }}</td>
    <td>{{ row.CorpShortName or "" }}</td>
    <td>{{ row.Meridian or "" }}</td>
    <td>
      <a href="{{ url_for('wellevent.details', wellevent_num = row.WellEvent) }}">Details</a>
    </td>
  </tr>
  {% endfor %}
</table>
</div>
<script>
$(function(){
  $("#accordion").accordion("option", "active", false);
}
)
</script>
{% endif %}

</html>

{% endblock %}