calcroyalties/src/app/views/wellevents.py
from flask import Blueprint, request, config, redirect, url_for, abort, render_template, flash, Response
import json, io, csv

import config
from .permission_handler import PermissionHandler
from src.util.apperror import AppError
from .main import get_proddate

wellevents = Blueprint('wellevents', __name__)

@wellevents.route('/wellevents', methods=['GET'])
def search():
    if not request.args: return render_template('wellevents/search.html')
    statement = """SELECT WellEventInfo.WellEvent, RTAHeader.RTPOperator, WellEventStatus.Status, WellLicence.Licensee, BAInfo.CorpShortName, WellFacilitylink.Facility, FacilityInfo.Name, WellEventLoc.Lat, WellEventLoc.Long
    FROM WellEventInfo
    LEFT OUTER JOIN RTAHeader ON WellEventInfo.WellEvent = RTAHeader.WellEvent
    AND (DATE('{proddate}') BETWEEN RTAHeader.StartDate AND RTAHeader.EndDate OR RTAHeader.StartDate IS NULL OR RTAHeader.StartDate = '')
    LEFT OUTER JOIN WellEventStatus ON WellEventInfo.WellEvent = WellEventStatus.WellEvent
    AND (DATE('{proddate}') BETWEEN WellEventStatus.StartDate AND WellEventStatus.EndDate OR WellEventStatus.StartDate IS NULL OR WellEventStatus.StartDate = '')
    LEFT OUTER JOIN BAInfo ON RTAHeader.RTPOperator = BAInfo.BAid
    AND (DATE('{proddate}') BETWEEN BAInfo.StartDate AND BAInfo.EndDate OR BAInfo.StartDate IS NULL OR BAInfo.StartDate = '')
    LEFT OUTER JOIN WellFacilityLink ON WellEventInfo.WellEvent = WellFacilityLink.WellEvent
    AND (DATE('{proddate}') BETWEEN WellFacilityLink.StartDate AND WellFacilityLink.EndDate OR WellFacilityLink.StartDate IS NULL OR WellFacilityLink.StartDate = '')
    LEFT OUTER JOIN FacilityInfo ON FacilityInfo.Facility = WellFacilityLink.Facility
    AND (DATE('{proddate}') BETWEEN FacilityInfo.StartDate AND FacilityInfo.EndDate OR FacilityInfo.StartDate IS NULL OR FacilityInfo.StartDate = '')
    LEFT OUTER JOIN WellEventLoc ON WellEventInfo.WellEvent = WellEventLoc.WellEvent
    LEFT OUTER JOIN WellInfo ON WellEventInfo.Well = WellInfo.Well
    AND (DATE('{proddate}') BETWEEN WellInfo.StartDate AND WellInfo.EndDate OR WellInfo.StartDate IS NULL OR WellInfo.StartDate = '')
    LEFT OUTER JOIN WellLicence ON WellLicence.WellLicence = WellInfo.WellLicence
    AND (DATE('{proddate}') BETWEEN WellLicence.StartDate AND WellLicence.EndDate OR WellLicence.StartDate IS NULL OR WellLicence.StartDate = '')
    WHERE (DATE('{proddate}') BETWEEN WellEventInfo.StartDate AND WellEventInfo.EndDate OR WellEventInfo.StartDate IS NULL OR WellEventInfo.StartDate = '')""".format(proddate=get_proddate())

    db = config.get_database()
    # the following allows us to check incoming arguments against a dictionary of allowed ones and match them with a relevant table name:
    argument_tables = {'WellEvent': 'WellEventInfo', 'Licensee': 'WellLicence', 'RTPOperator': 'RTAHeader', 'LSD': 'WellEventInfo', 'Section': 'WellEventInfo', 'Township': 'WellEventInfo', 'Range': 'WellEventInfo', 'Meridian': 'WellEventInfo'}
    kwargs = dict((k, v) for k, v in request.args.items() if v)  # this is to get rid of empty values coming from forms
    search_arguments = ""
    for arg in kwargs:
        if arg in argument_tables:
            compound = argument_tables[arg] + '.' + arg + '=' + '"' + kwargs[arg] + '"'
            search_arguments += " AND " + compound

    results = db.select_sql(statement + search_arguments)
    d = request.args.to_dict()
    output = 'browse'
    print('The Request is:',request.args.to_dict())
    if 'Output' in d:
        if d['Output'] == 'map':
            output = "map"
        elif d['Output'] == 'excel':
            output = "excel"
    print('The output is:',output)
    if results:
        if output == 'map':
            points = []
            for result in results:
                if result.Long:
                    json_obj = {}
                    json_obj['type'] = 'Feature'
                    json_obj['properties'] = {}
                    json_obj['properties']['name'] = result.WellEvent
                    json_obj['properties']['popupContent'] = '<b>%s</b> <br> Pool Name: %s<br><a href="/wellevent/%s">Details</a>' % (
                        result.WellEvent, result.RTPOperator, result.WellEvent)
                    json_obj['geometry'] = {}
                    json_obj['geometry']['type'] = 'Point'
                    json_obj['geometry']['coordinates'] = [round(result.Long * -1, 5), round(result.Lat, 5)]
                    points.append(json_obj)
            print('***** points: ', json.dumps(points))
            print('Center is...:',center_point(points))
            return render_template('map.html', results=json.dumps(points), center=center_point(points))

        elif output == 'excel':
            """ Export relies on python's csv module to generate csv, StringIO writer to simulate a file for csv,
                as we don't need to save it on hard drive, and dbi.execute and cursor to get raw results of a query
                as that's what we need for csv to work properly"""
            db.dbi.execute(statement + search_arguments)
            output = io.StringIO()
            writer = csv.writer(output, quoting=csv.QUOTE_NONNUMERIC)
            writer.writerow([i[0] for i in db.dbi.cursor.description])
            writer.writerows(db.dbi.cursor)
            return Response(output.getvalue(), mimetype="text/csv", headers={"Content-disposition": "attachment; filename=WellEvent_export.csv"})

        else:
            return render_template('wellevents/search.html', results=results, search_terms=request.args.to_dict())
    else:
        flash('No well events found.', 'error')
        return render_template('wellevents/search.html', search_terms=request.args.to_dict())

@wellevents.route('/wellevents/<wellevent_num>')
def details(wellevent_num):
    if not wellevent_num: redirect(url_for('wellevents.search'))
    try:
        db = config.get_database()
        statement="""SELECT WellEventInfo.*, RTAMineralOwnership.Product
        FROM WellEventInfo
        LEFT OUTER JOIN RTAMineralOwnership ON WellEventInfo.WellEvent = RTAMineralOwnership.WellEvent
        AND (DATE('{proddate}') BETWEEN RTAMineralOwnership.StartDate AND RTAMineralOwnership.EndDate)
        WHERE (DATE('{proddate}') BETWEEN WellEventInfo.StartDate AND WellEventInfo.EndDate)
        AND WellEventInfo.WellEvent = '{wellevent}'""".format(proddate=get_proddate(), wellevent=wellevent_num)
        wellevent = db.select_sql(statement)[0]
    except Exception as e:
        print(e)
        abort(404)

    statement_volumetric = """SELECT * From VolumetricInfo WHERE FromTo = '{wellevent}' AND DATE(ProdMonth) = DATE('{proddate}')""".format(wellevent=wellevent_num, proddate=get_proddate())
    volumetric = db.select_sql(statement_volumetric)

    try:
        well = db.select1('WellRoyaltyMaster', WellEvent=wellevent_num)

        statement_leases = """SELECT Lease.*, WellLeaseLink.PEFNInterest FROM Lease, WellLeaseLink WHERE WellLeaseLink.WellID="%s" AND Lease.ID=WellLeaseLink.LeaseID"""
        leases = db.select_sql(statement_leases % well.ID)

        statement_facilities = """SELECT FacilityInfo.* FROM FacilityInfo, WellFacilitylink WHERE FacilityInfo.Facility=WellFacilitylink.Facility AND WellFacilitylink.WellEvent="%s" """
        facilities = db.select_sql(statement_facilities % wellevent_num)
    except Exception as e:
        print(e)
        pass

    return render_template('wellevent/details.html', wellevent=wellevent, leases=leases, facilities=facilities, volumetric=volumetric, well=well)

def center_point(points):
    x,y  = points[0]['geometry']['coordinates']
    ux = x
    lx = x
    uy = y
    ly = y
    # print('---start',x,y)
    for point in points:
        x,y = point['geometry']['coordinates']
        if x > ux : ux = x
        if x < lx : lx = x
        if y > uy : uy = y
        if y < ly : ly = y
        # print('---',point['geometry']['coordinates'])

    # print('+++', ux, lx)
    # print('+++', uy, ly)
    return (lx + ((ux - lx) / 2)), (ly + ((uy - ly) / 2))

calcroyalties/src/app/views/worksheet.py
import sys
import traceback
from flask import Blueprint, request, config, render_template

import config
from src.util.apperror import AppError
from src.util.appdate import prod_month_to_date
from src.util.app_formatter import format_gorr
from src.database.data_structure import DataStructure
import pdfkit

worksheet = Blueprint('worksheet', __name__)


@worksheet.route('/worksheet')
def calc_worksheet():
    args = request.args.to_dict()
    db = config.get_database()
    calcs = db.select('Calc', **args)
    result = ""
    for calc in calcs:
        result += generate_worksheet_from_calc(calc)
        # result += "<hr>"

    return result


@worksheet.route('/worksheettopdf')
def calc_worksheettopdf():
    try:
        args = request.args.to_dict()
        print(args)
        db = config.get_database()
        calcs = db.select('Calc', **args)
        result = ""
        for calc in calcs:
            result += generate_worksheet_from_calc(calc, 'n')
            result += "<hr>"

        # text_file = open("out.html", "w", encoding="utf-8")
        # text_file.write(result)
        # text_file.write(result. .encode("UTF-8"))
        # text_file.close()

        print("about to set path")
        path_wkthmltopdf = r'C:\Program Files (x86)\wkhtmltopdf\bin\wkhtmltopdf.exe'
        print("about to set config")
        configpdf = pdfkit.configuration(wkhtmltopdf=path_wkthmltopdf)
        print("about to pdfkit")
        pdfkit.from_string(result, 'out.pdf', configuration=configpdf)

        return "pdf should have been created"

    except Exception as e:
        print('PDF worksheet: ***Error:', e)
        traceback.print_exc(file=sys.stdout)
        tb = traceback.format_exc()
        return "<h2>Error generating pdf" + \
               '<plaintext>' + tb + '</plaintext>'


def generate_worksheet_from_calc(calc, with_js='y'):
    """
    Generate html for the calc row that is passed
    :param calc: a full calc record
    :param with_js: default is 'y' only other option is 'n' and should only be used to work around a
                    pdf generation issue
    :return: html of the worksheet for the calc record
    """
    try:
        db = config.get_database()
        if calc.Entity == 'Well':
            well = db.select1('WellRoyaltyMaster', ID=calc.EntityID)
        else:
            well = None
        entity_lease_link_array = db.select('EntityLeaseLink', Entity=calc.Entity, EntityID=calc.EntityID)
        if len(entity_lease_link_array) == 0:
            raise AppError("There were no well_lease_link records for " + str(calc.WellID) + str(calc.ProdMonth))
        entity_lease_link = entity_lease_link_array[0]
        royalty = db.select1('LeaseRoyaltyMaster', ID=calc.LeaseID)
        lease = db.select1('Lease', ID=calc.LeaseID)

        history = db.select_sql("""SELECT *
                   from Calc
                   WHERE ProdMonth = "{}" and LeaseID = "{}" and Entity = "{}" and EntityID = "{}"
                   and Product = "{}" and RPBA = "{}"
                   order by ExtractDate""".format(calc.ProdMonth, calc.LeaseID, calc.Entity, calc.EntityID,
                                                  calc.Product, calc.RPBA))
        # history = db.select_sql("""SELECT ID, ExtractDate, BaseNetRoyaltyValue, GorrNetRoyaltyValue
        #            from Calc
        #            WHERE ProdMonth = "{}" and LeaseID = "{}" and Entity = "{}" and EntityID = "{}"
        #            and Product = "{}" and RPBA = "{}"
        #            order by ExtractDate""".format(calc.ProdMonth, calc.LeaseID, calc.Entity, calc.EntityID,
        #                                           calc.Product, calc.RPBA))

        prev_BaseNetRoyaltyValue = 0.0
        prev_GorrNetRoyaltyValue = 0.0
        i = 0
        for h in history:
            h.BookedBaseNetRoyaltyValue = h.BaseNetRoyaltyValue - prev_BaseNetRoyaltyValue
            h.BookedGorrNetRoyaltyValue = h.GorrNetRoyaltyValue - prev_GorrNetRoyaltyValue
            h.Booked = h.BookedBaseNetRoyaltyValue + h.BookedGorrNetRoyaltyValue
            prev_BaseNetRoyaltyValue = h.BaseNetRoyaltyValue
            prev_GorrNetRoyaltyValue = h.GorrNetRoyaltyValue
            # Set the original calc record to the history record the one before this one
            if h.ExtractDate == calc.ExtractDate and i > 0:
                calc.original(history[i-1])

            i += 1

        monthly_array = db.select('Monthly', ExtractDate=calc.ExtractDate, Entity=calc.Entity, EntityID=calc.EntityID,
                                  prodMonth=calc.ProdMonth, product=calc.Product, RPBA=calc.RPBA)
        if len(monthly_array) == 0:
            raise AppError("There were no monthly records for well: " + str(calc.WellID) + " ProdDate: " +
                           str(calc.ProdMonth) + " Product: " + calc.Product)
        monthly = monthly_array[0]  # if there are multiple pick the first one

        ba = db.select1('BAInfo', BAid=monthly.RPBA, BAType='RTP')

        calc_specific = DataStructure(calc.RoyaltySpecific)
        rtp_info = db.select1('RTPInfo', WellEvent=well.WellEvent, Product=calc.Product, Payer=monthly.RPBA,
                              Date=prod_month_to_date(calc.ProdMonth))

        royalty.format_gorr = format_gorr(calc.Gorr)

        return render_template('worksheet/calc_worksheet.html',
                               with_js=with_js,
                               well=well, rm=royalty, m=monthly, lease=lease,
                               calc=calc, calc_sp=calc_specific, entity_lease_link=entity_lease_link,
                               ba=ba, rtp_info=rtp_info, history=history)
    except Exception as e:
        print('views.worksheet: ***Error:', e)
        traceback.print_exc(file=sys.stdout)
        tb = traceback.format_exc()
        return "<h2>Error displaying worksheet for " + calc.Entity + " %s</h2><br>" % calc.EntityID + str(e) + \
               '<plaintext>' + tb + '</plaintext>'


def generate_pdfworksheet_from_calc(calc):
    try:
        db = config.get_database()
        if calc.Entity == 'Well':
            well = db.select1('WellRoyaltyMaster', ID=calc.EntityID)
        else:
            well = None
        entity_lease_link_array = db.select('EntityLeaseLink', Entity=calc.Entity, EntityID=calc.EntityID)
        if len(entity_lease_link_array) == 0:
            raise AppError("There were no well_lease_link records for " + str(calc.WellID) + str(calc.ProdMonth))
        entity_lease_link = entity_lease_link_array[0]
        royalty = db.select1('LeaseRoyaltyMaster', ID=calc.LeaseID)
        lease = db.select1('Lease', ID=calc.LeaseID)

        history = db.select_sql("""SELECT ID, ExtractDate, BaseNetRoyaltyValue, GorrNetRoyaltyValue
                   from Calc
                   WHERE ProdMonth = "{}" and LeaseID = "{}" and Entity = "{}" and EntityID = "{}"
                   and Product = "{}" and RPBA = "{}"
                   order by ExtractDate""".format(calc.ProdMonth, calc.LeaseID, calc.Entity, calc.EntityID,
                                                  calc.Product, calc.RPBA))

        prev_BaseNetRoyaltyValue = 0.0
        prev_GorrNetRoyaltyValue = 0.0
        for h in history:
            h.BookedBaseNetRoyaltyValue = h.BaseNetRoyaltyValue - prev_BaseNetRoyaltyValue
            h.BookedGorrNetRoyaltyValue = h.GorrNetRoyaltyValue - prev_GorrNetRoyaltyValue
            h.Booked = h.BookedBaseNetRoyaltyValue + h.BookedGorrNetRoyaltyValue
            prev_BaseNetRoyaltyValue = h.BaseNetRoyaltyValue
            prev_GorrNetRoyaltyValue = h.GorrNetRoyaltyValue

        monthly_array = db.select('Monthly', ExtractDate=calc.ExtractDate, Entity=calc.Entity, EntityID=calc.EntityID,
                                  prodMonth=calc.ProdMonth, product=calc.Product, RPBA=calc.RPBA)
        if len(monthly_array) == 0:
            raise AppError("There were no monthly records for well: " + str(calc.WellID) + " ProdDate: " +
                           str(calc.ProdMonth) + " Product: " + calc.Product)
        monthly = monthly_array[0]  # if there are multiple pick the first one

        ba = db.select1('BAInfo', BAid=monthly.RPBA, BAType='RTP')

        calc_specific = DataStructure(calc.RoyaltySpecific)
        rtp_info = db.select1('RTPInfo', WellEvent=well.WellEvent, Product=calc.Product, Payer=monthly.RPBA,
                              Date=prod_month_to_date(calc.ProdMonth))

        royalty.format_gorr = format_gorr(calc.Gorr)

        return render_template('worksheet/pdfcalc_worksheet.html',
                               well=well, rm=royalty, m=monthly, lease=lease,
                               calc=calc, calc_sp=calc_specific, entity_lease_link=entity_lease_link,
                               ba=ba, rtp_info=rtp_info, history=history)
    except Exception as e:
        print('views.worksheet: ***Error:', e)
        traceback.print_exc(file=sys.stdout)
        tb = traceback.format_exc()
        return "<h2>Error displaying worksheet for " + calc.Entity + " %s</h2><br>" % calc.EntityID + str(e) + \
               '<plaintext>' + tb + '</plaintext>'

calcroyalties/src/app/templates/wellevents/details.html
{% extends "layout.html" %}
{% block body %}

<form>
    <fieldset>
        <legend><h3>Well Event {{ wellevent.WellEvent }}</h3></legend>
        <table cellpadding="5">
            <tr>
                <td><label for="HorizonPool">Horizon Pool</label></td>
                <td><input type="text" id="HorizonPool" value="{{ wellevent.HorizonPool }}" disabled /></td>
                <td><label for="PoolName">Pool Name</label></td>
                <td><input type="text" id="PoolName" value="{{ wellevent.PoolName }}" disabled /></td>
            </tr>
            <tr>
                <td><label for="Meridian">Meridian</label></td>
                <td><input type="text" id="Meridian" value="{{ wellevent.Meridian }}" disabled /></td>
                <td><label for="Range">Range</label></td>
                <td><input type="text" id="Range" value="{{ wellevent.Range }}" disabled /></td>
            </tr>
            <tr>
                <td><label for="Township">Township</label></td>
                <td><input type="text" id="Township" value="{{ wellevent.Township }}" disabled /></td>
                <td><label for="Section">Section</label></td>
                <td><input type="text" id="Section" value="{{ wellevent.Section }}" disabled /></td>
            </tr>
            <tr>
                <td><label for="LSD">LSD</label></td>
                <td><input type="text" id="LSD" value="{{ wellevent.LSD }}" disabled /></td>
                <td><label for="GCIStatus">GCI Status</label></td>
                <td><input type="text" id="GCIStatus" value="{{ wellevent.GCIStatus }}" disabled /></td>
            </tr>
            <tr>
                <td><label for="Product">Product</label></td>
                <td><input type="text" id="Product" value="{{ wellevent.Product }}" disabled /></td>
                <!--<td><label for="Volume">Volume</label></td>-->
                <!--<td><input type="text" id="Volume" value="{{ wellevent.Volume }}" disabled /></td>-->
            </tr>
        </table>
    </fieldset>
</form>

{% if well %}
<br />
<form>
    <fieldset>
        <legend><h3>Well {{ well.ID }}</h3></legend>
        <table cellpadding="5">
            <tr>
                <td><label for="Province">Province</label></td>
                <td><input type="text" id="Province" value="{{ well.Prov }}" disabled /></td>
                <td><label for="WellType">Well Type</label></td>
                <td><input type="text" id="WellType" value="{{ well.WellType }}" disabled /></td>
            </tr>
            <tr>
                <td><label for="Classification">Classification</label></td>
                <td><input type="text" id="Classification" value="{{ well.Classification }}" disabled /></td>
                <td><label for="RoyaltyClassification">Royalty Classification</label></td>
                <td><input type="text" id="RoyaltyClassification" value="{{ well.RoyaltyClassification }}" disabled /></td>
            </tr>
            <tr>
                <td colspan="2"><a href="{{ url_for('worksheet.calc_worksheet', WellId = well.ID) }}">Calculated worksheet</a></td>
            </tr>
        </table>
    </fieldset>
</form>
{% endif %}

{% if leases %}
<br />
<fieldset>
<legend><h3><b>{{leases|length}}</b> leases attached:</h3></legend>
    <ul>
    {% for lease in leases %}
    <li><a href="/lease/{{ lease.ID }}">{{ lease.ID }} &mdash; {{lease.PEFNInterest }}</a></li>
    {% endfor %}
    </ul>
</fieldset>
{% endif %}

{% if facilities %}
<br/>
<fieldset>
<legend><h3><b>{{facilities|length}}</b> facilities attached:</h3></legend>
    <ul>
    {% for facility in facilities %}
    <li><a href="/facility/{{ facility.Facility }}">{{ facility.Facility }}</a></li>
    {% endfor %}
    </ul>
</fieldset>
{% endif %}

{% if volumetric %}
<br />
<fieldset>
<legend><h3><b>{{volumetric|length}}</b> volumetric records:</h3></legend>
<table style="width:50%" class="table-results table-striped">
  <!--<tr>-->
    <!--<td colspan=12><h3><b>{{volumetric|length}}</b> volumetric records:</h3></td>-->
  <!--</tr>-->
  <tr>
    <th>Production Month</th>
    <th>Activity</th>
    <th>Product</th>
    <th>Volume</th>
    <th>Energy</th>
  </tr>
  {% for row in volumetric %}
  <tr>
    <td>{{ row.ProdMonth or "" }}</td>
    <td>{{ row.Activity or "" }}</td>
    <td>{{ row.Product or "" }}</td>
    <td>{{ row.Volume or "" }}</td>
    <td>{{ row.Energy or "" }}</td>
  </tr>
  {% endfor %}
</table>
</fieldset>
{% endif %}

{% endblock %}

calcroyalties/src/app/templates/wellevents/oldresults.html
<div id="modal">
</div>

<table style="width:100%" class="results_table">
  <tr>
    <td colspan=13><b>{{results|length}}</b> results found</td>
  </tr>
  <tr>
    <th>Well Event</th>
    <th>Province</th>
    <th>FN Reserve</th>
    <th>Lessor</th>
    <th>Actions</th>
  </tr>
  {% for row in results %}
  <tr>
    <td>{{ row.WellEvent or "" }}</td>
    <td>{{ row.Prov or "" }}</td>
    <td>{{ row.FNReservce or "" }}</td>
    <td>{{ row.Lessor or "" }}</td>
    <td>
      <a href="{{ url_for('wellevent_details', wellevent_num = row.ID) }}">Details</a>
    <!--  Edit / view icons from wells
    <a href="#" title="Edit" class="icon icon-edit" onclick=openInfo({{ row.ID }})></a>
    &nbsp;
    <a href="/worksheet?WellId={{ row.ID }}" title="Worksheet" class="icon icon-text-document"></a>
    -->
    </td>
  </tr>
  {% endfor %}
</table>


<script>
function openInfo(id) {
  var idObject = {ID:id}
  console.log(idObject);
  $.ajax({
    url: "/api/lease",
    data: idObject,
  })
  .done(function(data){
    $('#modal').html(data)});
  }
</script>