calcroyalties/src/app/views/leases.py
from flask import Blueprint, render_template, abort, request, json, redirect, url_for, flash

import config
from src.database.data_structure import DataStructure
from .permission_handler import PermissionHandler
from .main import get_proddate

leases = Blueprint('leases', __name__)

@leases.route('/leases/')
def search():
    if not request.args: return render_template('leases/search.html')
    try:
        db = config.get_database()
        argument_tables = {'Prov': 'Lease', 'ID': 'Lease'}  # allowed Property:Table pairs
        kwargs = dict((k, v) for k, v in request.args.items() if v and k in argument_tables)  # this is to get rid
        # of empty values coming from forms and convert multidict to dict and to check if argument is allowed
        search_arguments = ""
        for arg in kwargs:
            compound = argument_tables[arg] + '.' + arg + '=' + '"' + kwargs[arg] + '"'
            search_arguments += " AND " + compound
        statement = """SELECT * FROM Lease
                       WHERE DATE("{proddate}") BETWEEN Lease.StartDate and Lease.EndDate
                    """.format(proddate=get_proddate()) + search_arguments
        result = db.select_sql(statement)
        if result:
            return render_template('leases/search.html', results=result, search_terms=request.args.to_dict())
        else:
            flash('No matching leases found', 'error')
            return render_template('leases/search.html', search_terms=request.args.to_dict())
    except Exception as e:
        print(e)
        abort(404)

@leases.route('/leases/<lease_num>', methods=['GET', 'POST'])
def details(lease_num):
    db = config.get_database()
    if request.method == 'POST' and request.form['action'] == 'delete':
        print(request.form)
        print('about to delete')
        try:
            lease_id = int(request.form['ID'])
            print(lease_id)
            db.delete('Lease', lease_id)
            db.delete('LeaseRoyaltyMaster', lease_id)
            flash('Successfully deleted lease ' + str(lease_id))
            return redirect(url_for('leases.search'))
        except Exception as e:
            print('Failed to delete lease ' + request.form['ID'], e)
            flash('Failed to delete lease ' + request.form['ID'])
            return redirect(url_for('leases.search'))
    elif request.method == 'POST' and request.form['action'] == 'update':
        print('about to update')
        ds = db.select1('Lease', ID=lease_num)
        print(ds)
        try:
            for i in request.form:
                if i != 'action':
                    setattr(ds, i, request.form[i])
            print(ds)
            db.update(ds)
            flash('Successfully updated lease ' + lease_num)
            return redirect(url_for('leases.details', lease_num=lease_num))
        except Exception as e:
            flash('Couldn\'t update a lease')
            print('Couldn\'t update a lease: ', e)
            return redirect(url_for('leases.search'))
    elif request.method == 'GET':
        try:
            db = config.get_database()
            lease = db.select1('Lease', ID=lease_num)
            royaltymaster = db.select1('LeaseRoyaltyMaster', ID=lease_num)
            wellevent_statement = """SELECT WellEventInfo.* FROM WellEventInfo, WellLeaseLink
                           WHERE WellLeaseLink.LeaseID="%s"
                           AND WellEventInfo.WellEvent=WellLeaseLink.WellID"""
            # wellevents = db.select_sql(wellevent_statement % lease_num)  # not sure what the situation is here, None for now
            wellevents = None
            return render_template('leases/details.html', new = False, lease = lease, royaltymaster = royaltymaster, wellevents=wellevents)
        except Exception as e:
            print(e)
            abort(404)

@leases.route('/leases/<lease_num>/wells.json', methods=['GET', 'POST'])
def wells(lease_num):
    db = config.get_database()
    wells_statement = """SELECT WellRoyaltyMaster.* FROM WellRoyaltyMaster, WellLeaseLink
               WHERE WellLeaseLink.LeaseID="%s"
               AND WellRoyaltyMaster.ID=WellLeaseLink.WellID"""
    wells = db.select_sql(wells_statement % lease_num)
    result = []
    for w in wells:
        result.append(w.json_dumps())
    return json.dumps(result)

@leases.route('/leases/new', methods=['GET', 'POST'])
def new():
    db = config.get_database()
    if request.method == 'GET':
        return render_template('leases/details.html', new = True, lease = None, royaltymaster = None)
    elif request.method == 'POST' and request.form['action'] == 'cancel':
        return redirect(url_for('leases.search'))
    elif request.method == 'POST' and request.form['action'] == 'add':
        ds = DataStructure()
        setattr(ds, '_table_name', 'Lease')
        for i in request.form:
            if i != 'action':
                setattr(ds, i, request.form[i])
        try:
            new_id = db.insert(ds)
            flash('Lease successfully added')
            return redirect(url_for('leases.details', lease_num=new_id))
        except Exception as e:
            flash('Couldn\'t add a new lease')
            print('Couldn\'t add a new lease: ', e)
            return redirect(url_for('leases.search'))


"""
@leases.route('/api/leaseresults', methods=['GET', 'POST'])
def results():
    if not request.is_xhr: abort(404)
    try:
        db = config.get_database()
        req_data = request.get_json()
        results = db.select('Lease', **req_data)
        print(req_data, results)
        return render_template('leases/results.html', results = results)
    except Exception as e:
        print(e)
        return json.dumps({'success': False}), 404, {'ContentType': 'application/json'}
"""

"""
GET /leases - empty search form
GET /leases?searchparams - search results
GET /leases/1 - lease details
POST /leases - adds a new lease, returns new ID
PUT /leases/1 - updates a lease, returns 200
DELETE /leases/1 - deletes a lease, returns 200
"""

calcroyalties/src/app/templates/leases/Xresults.html
<div id="modal">
</div>

<table style="width:100%" class="results_table">
  <caption><b>{{results|length}}</b> results found</caption>
  <tr>
    <th>Lease Type</th>
    <th>Lease ID</th>
    <th>Province</th>
    <th>FN Reserve</th>
    <th>FN Band ID</th>
    <th>Lessor</th>
  </tr>
  {% for row in results %}
  <tr>
    <td>{{ row.LeaseType }}</td>
    <td><a href="{{ url_for('leases.details', lease_num = row.ID) }}">{{ row.ID or "" }}</a></td>
    <td>{{ row.Prov or "" }}</td>
    <td>{{ row.FNReserve or "" }}</td>
    <td>{{ row.FNBandID or "" }}</td>
    <td>{{ row.Lessor or "" }}</td>
  </tr>
  {% endfor %}
</table>


<script>
function openInfo(id) {
  var idObject = {ID:id}
  console.log(idObject);
  $.ajax({
    url: "/api/lease",
    data: idObject,
  })
  .done(function(data){
    $('#modal').html(data)});
  }
</script>

calcroyalties/src/app/templates/leases/details.html
{% extends 'layout.html' %}
{% block body %}
<style>
div.float {
    border: 1px solid #AAAAAA;
    float: left;
}
</style>

<form id="leaseForm" method="POST">
    <fieldset>
        <legend><h3>Lease {{ lease.Lease }}</h3></legend>
        <table cellpadding="5">
            <tr>
                <td><label for="LeaseType">Lease Type</label> <sup><i data-help="LeaseRoyaltyMaster.LeaseType" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="LeaseType" value="{{ lease.LeaseType }}" /></td>
                <td><label for="Province">Province</label></td>
                <td><input type="text" name="Prov" value="{{ lease.Prov }}" /></td>
            </tr>
            <tr>
                <td><label for="FNReserve">FNReserve</label></td>
                <td><input type="text" name="FNReserveID" value="{{ lease.FNReserveID }}" /></td>
                <td><label for="FNBandID">FNBandID</label></td>
                <td><input type="text" name="FNBandID" value="{{ lease.FNBandID }}" /></td>
            </tr>
            <tr>
                <td><label for="Notes">Notes</label></td>
                <td colspan="3"><input style="width:100%" type="text" name="Notes" value="{{ lease.Notes }}" /></td>
            </tr>

            <tr>
                <td colspan="4">&nbsp;</td>
                {% if new == False %}
                <td><button type="submit" name="action" value="delete">Delete</button></td>
                <td><button type="submit" name="action" value="update">Update</button></td>
                {% else %}
                <td><button type="submit" name="action" value="cancel">Cancel</button></td>
                <td><button type="submit" name="action" value="add">Add</button></td>
                {% endif %}
            </tr>

            <tr>
                <td><label for="ID">ID</label> <sup><i data-help="LeaseRoyaltyMaster.ID" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="ID" value="{{ royaltymaster.ID }}" /></td>
                <td><label for="ValuationMethod">Valuation Method</label></td>
                <td><input type="text" name="ValuationMethod" value="{{ royaltymaster.ValuationMethod }}" /></td>

            </tr>

            <tr>
                <td><label for="StartDate">StartDate</label> <sup><i data-help="LeaseRoyaltyMaster.StartDate" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="StartDate" value="{{ royaltymaster.StartDate }}" /></td>
                <td><label for="EndDate">EndDate</label> <sup><i data-help="LeaseRoyaltyMaster.EndDate" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="EndDate" value="{{ royaltymaster.EndDate }}" /></td>
            </tr>

            <tr>
                <td><label for="RightsGranted">RightsGranted</label> <sup><i data-help="LeaseRoyaltyMaster.RightsGranted" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="RightsGranted" value="{{ royaltymaster.RightsGranted }}" /></td>
                <td><label for="RoyaltyScheme">RoyaltyScheme</label> <sup><i data-help="LeaseRoyaltyMaster.RoyaltyScheme" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="RoyaltyScheme" value="{{ royaltymaster.RoyaltyScheme }}" /></td>
            </tr>
            <tr>
                <td><label for="CrownMultiplier">CrownMultiplier</label> <sup><i data-help="LeaseRoyaltyMaster.CrownMultiplier" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="CrownMultiplier" value="{{ royaltymaster.CrownMultiplier }}" /></td>
                <td><label for="CrownModifier">CrownModifier</label> <sup><i data-help="LeaseRoyaltyMaster.CrownModifier" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="CrownModifier" value="{{ royaltymaster.CrownModifier }}" /></td>
            </tr>
            <tr>
                <td><label for="OilPriceBasedOn">OilPriceBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.OilPriceBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="OilPriceBasedOn" value="{{ royaltymaster.OilPriceBasedOn }}" /></td>
                <td><label for="GasPriceBasedOn">GasPriceBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.GasPriceBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="GasPriceBasedOn" value="{{ royaltymaster.GasPriceBasedOn }}" /></td>
            </tr>
            <tr>
                <td><label for="ProductsPriceBasedOn">ProductsPriceBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.ProductsPriceBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="ProductsPriceBasedOn" value="{{ royaltymaster.ProductsPriceBasedOn }}" /></td>
                <td><label for="OilValueBasedOn">OilValueBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.OilValueBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="OilValueBasedOn" value="{{ royaltymaster.OilValueBasedOn }}" /></td>
            </tr>
            <tr>
                <td><label for="GasValueBasedOn">GasValueBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.GasValueBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="GasValueBasedOn" value="{{ royaltymaster.GasValueBasedOn }}" /></td>
                <td><label for="ProductsValueBasedOn">ProductsValueBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.ProductsValueBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="ProductsValueBasedOn" value="{{ royaltymaster.ProductsValueBasedOn }}" /></td>
            </tr>

            <tr>
                <td><label for="OilRoyaltyBasedOn">OilRoyaltyBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.OilRoyaltyBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="OilRoyaltyBasedOn" value="{{ royaltymaster.OilRoyaltyBasedOn }}" /></td>
                <td><label for="GasRoyaltyBasedOn">GasRoyaltyBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.GasRoyaltyBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="GasRoyaltyBasedOn" value="{{ royaltymaster.GasRoyaltyBasedOn }}" /></td>
            </tr>
            <tr>
                <td><label for="ProductsRoyaltyBasedOn">ProductsRoyaltyBasedOn</label> <sup><i data-help="LeaseRoyaltyMaster.ProductsRoyaltyBasedOn" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="ProductsRoyaltyBasedOn" value="{{ royaltymaster.ProductsRoyaltyBasedOn }}" /></td>
                <td><label for="TransDeducted">TransDeducted</label> <sup><i data-help="LeaseRoyaltyMaster.TransDeducted" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="TransDeducted" value="{{ royaltymaster.TransDeducted }}" /></td>
            </tr>
            <tr>
                <td><label for="ProcessingDeducted">ProcessingDeducted</label> <sup><i data-help="LeaseRoyaltyMaster.ProcessingDeducted" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="ProcessingDeducted" value="{{ royaltymaster.ProcessingDeducted }}" /></td>
                <td><label for="GCADeducted">GCADeducted</label> <sup><i data-help="LeaseRoyaltyMaster.GCADeducted" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="GCADeducted" value="{{ royaltymaster.GCADeducted }}" /></td>
            </tr>
            <tr>
                <td><label for="Gorr">Gorr</label> <sup><i data-help="LeaseRoyaltyMaster.Gorr" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="Gorr" value="{{ royaltymaster.Gorr }}" /></td>
                <td><label for="OverrideRoyaltyClassification">OverrideRoyaltyClassification</label> <sup><i data-help="LeaseRoyaltyMaster.OverrideRoyaltyClassification" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="OverrideRoyaltyClassification" value="{{ royaltymaster.OverrideRoyaltyClassification }}" /></td>
            </tr>
            <tr>
                <td><label for="MinRoyaltyRate">MinRoyaltyRate</label> <sup><i data-help="LeaseRoyaltyMaster.MinRoyaltyRate" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="MinRoyaltyRate" value="{{ royaltymaster.MinRoyaltyRate }}" /></td>
                <td><label for="MaxRoyaltyRate">MaxRoyaltyRate</label> <sup><i data-help="LeaseRoyaltyMaster.MaxRoyaltyRate" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="MaxRoyaltyRate" value="{{ royaltymaster.MaxRoyaltyRate }}" /></td>
            </tr>
            <tr>
                <td><label for="MinRoyaltyDollar">MinRoyaltyDollar</label> <sup><i data-help="LeaseRoyaltyMaster.MinRoyaltyDollar" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="MinRoyaltyDollar" value="{{ royaltymaster.MinRoyaltyDollar }}" /></td>
                <td><label for="Notes">Notes</label> <sup><i data-help="LeaseRoyaltyMaster.Notes" class="fa fa-question-circle help"></i></sup></td>
                <td><input type="text" name="Notes" value="{{ royaltymaster.Notes }}" /></td>
            </tr>

        </table>
    </fieldset>
</form>

<br>
<div id="wellsAccordion">
    <h3>Show wells</h3>
    <div id="wells"></div>
</div>

<script>
    $(function() {
  $('.help').on('click', function(){showHelp()});

  $("#help-modal").dialog({
    modal: true,
    autoOpen: false,
    buttons: {
      OK: function() {$(this).dialog("close")}
    }
  });

        $('#wellsAccordion').accordion({
            collapsible:true,
            active:false,
            heightStyle:'auto',
            animate:false
        });
    });

    var wells_cache;  // store wells so we don't run the request every time we open/close the accordion
    $('#wellsAccordion').click(function(e){
            if (wells_cache) {
                $('#wells').html('<ul>' + wells_cache + '</ul>');
                $('#wellsAccordion').accordion('refresh');
            } else {
                $.get('/leases/' + '{{ lease.ID }}' + '/wells.json', function(data){
                    data = JSON.parse(data);
                    var items = [];
                    $.each(data, function (id, item) {
                        item = JSON.parse(item);
                        items.push('<li><a href="/wells/' + item.ID +'">' + item.ID + '</a></li>');
                    });
                    wells_cache = items.join('');
                    $('#wells').html('<ul>' + wells_cache + '</ul>');
                    $('#wellsAccordion').accordion('refresh');
                })
            }
        }
    )

function showHelp() {
  var helpItem = $(event.target).data('help');
  $.get('/lookups/help', {item: helpItem})
    .done(function(data) {
      $('#help-modal-text').html(data);
    })
    .fail(function(data) {
      $('#help-modal-text').html('Failed to get help for ', helpItem);
    })
    .always(function(data) {
      $('#help-modal').dialog({title: 'Help for ' + helpItem});
      $('#help-modal').dialog('open');
    });
 }

</script>
<div id="help-modal">
  <div id="help-modal-text">

  </div>
</div>

{% endblock %}

calcroyalties/src/app/templates/leases/results.html
<div id="modal">
</div>

<table style="width:100%" class="results_table">
  <caption><b>{{results|length}}</b> results found</caption>
  <tr>
    <th>Lease Type</th>
    <th>Lease ID</th>
    <th>Province</th>
    <th>FN Reserve</th>
    <th>FN Band ID</th>
    <th>Lessor</th>
  </tr>
  {% for row in results %}
  <tr>
    <td>{{ row.LeaseType }}</td>
    <td><a href="{{ url_for('leases.details', lease_num = row.ID) }}">{{ row.ID or "" }}</a></td>
    <td>{{ row.Prov or "" }}</td>
    <td>{{ row.FNReserve or "" }}</td>
    <td>{{ row.FNBandID or "" }}</td>
    <td>{{ row.Lessor or "" }}</td>
  </tr>
  {% endfor %}
</table>


<script>
function openInfo(id) {
  var idObject = {ID:id}
  console.log(idObject);
  $.ajax({
    url: "/api/lease",
    data: idObject,
  })
  .done(function(data){
    $('#modal').html(data)});
  }
</script>

calcroyalties/src/app/templates/leases/search.html
{% extends "layout.html" %}
{% block body %}
<script>
  $(function() {
  	$('#tabs').tabs();
    $('#search-accordion').accordion({
      collapsible:true,
      heightStyle:'content',
      animate:false
    });
    $('#search-basic, #search-advanced').button({
      icons: {primary: 'ui-icon-search'}
    });
  });
</script>

<h2>Lease Search</h2>

<div id="search-accordion">
  <h3>Search Criteria</h3>
  <div>
  	<div id="tabs">
  	  <ul>
  	    <li><a href="#tabs-basic">Basic search</a></li>
  	    <li><a href="#tabs-advanced">Advanced search</a></li>
  	  </ul>

  	  <div id="tabs-basic">
      <form name="search-basic" action="/leases" method="get">
  	    Lease ID<sup><i data-help="LeaseRoyaltyMaster.ID" class="fa fa-question-circle help"></i></sup>
        <br>
        <input id='ID' name="ID" value="{% if search_terms %}{{ search_terms['ID'] }}{% endif %}" />
        <br>
        <br>
        Province
        <br>
        <input id='Prov' name="Prov" value="{% if search_terms %}{{ search_terms['Prov'] }}{% endif %}" />
        <br>
        <br>
          <button type="submit" id='search-basic'>Search</button>&nbsp;<a href="{{ url_for('leases.new') }}">Create new</a>
       </form>
  	  </div>

  	  <div id="tabs-advanced">
      <form name="search-advanced" action="/leases" method="get">
  	    Province
        <br>
        <input id='well-search-prov' name="Province" value="{% if search_terms %}{{ search_terms['Prov'] }}{% endif %}"/>
        <br>
        <br>
        Well Type
        <br>
        <input id='well-search-type' name="FNReserve" value="{% if search_terms %}{{ search_terms['FNReserve'] }}{% endif %}" />
        <br>
        <br>
        <button type="submit" id='search-advanced'>Search</button>
      </form>
  	  </div>

  	</div>
  </div>
</div>

{% if results %}
<div id='results-table'>
<table style="width:100%" class="results_table table-striped">
  <caption><b>{{results|length}}</b> results found</caption>
  <tr>
    <th>ID</th>
    <th>Lease Type</th>
    <th>Province</th>
    <th>FN Reserve</th>
    <th>FN Band ID</th>
  </tr>
  {% for row in results %}
  <tr>
    <td><a href="{{ url_for('leases.details', lease_num = row.ID) }}">{{ row.ID or "" }}</a></td>
    <td>{{ row.LeaseType or "" }}</td>
    <td>{{ row.Prov or "" }}</td>
    <td>{{ row.FNReserve or "" }}</td>
    <td>{{ row.FNBandID or "" }}</td>
  </tr>
  {% endfor %}
</table>
</div>
<script>
// collapses the accordion if there are search results
$(function(){
  $("#search-accordion").accordion("option", "active", false);
})
</script>
{% endif %}

</html>

{% endblock %}